# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from report_screen import report_screen
import openpyxl


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWin = MainWindow
        self.MainWin.setObjectName("MainWindow")
        self.MainWin.setFixedSize(800, 600)
        self.MainWin.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.MainWin.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(self.MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(225, 470, 350, 70))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "    border-image: url(:/main_screen/main_button.png);\n"
            "}\n"
            "QPushButton::hover{\n"
            "    border-image: url(:/main_screen/main_button_hover.png);\n"
            "}"
        )
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(254, 60))
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.click_button)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setStyleSheet("border-image: url(:/main_screen/main_screen.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images_project1/main_screen.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 600, 100))
        self.label_2.setStyleSheet("border-image: url(:/main_screen/main_text.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images_project1/main_text.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(175, 300, 450, 50))
        font = QtGui.QFont()
        font.setFamily("마루 부리 Beta")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(
            "border-image: url(:/main_screen/main_text_in.png);\n"
            "color: rgb(0, 0, 0);"
        )
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.MainWin.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWin)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWin.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "ID를 입력해주세요!"))

    def click_button(self):
        self.pushButton.setCursor(QtCore.Qt.ClosedHandCursor)
        inp = self.lineEdit.text()
        if inp.isdigit():
            ID_index = self.check_id_valid(int(inp))
            if ID_index:
                self.MainWin.hide()
                self.report_screen_dialog = QtWidgets.QDialog()
                self.report_screen_dialog.setFixedSize(1300, 700)
                self.report_screen = report_screen()
                self.report_screen.setupUi(self.report_screen_dialog)

                self.report_screen.initialize_screen(ID_index)
                self.report_screen_dialog.exec()
                self.MainWin.show()
            else:
                reply = QtWidgets.QMessageBox.warning(
                    QtWidgets.QMessageBox(),
                    "ID Error",
                    "ID가 잘못되었습니다!",
                    QtWidgets.QMessageBox.Ok,
                )
        else:
            reply = QtWidgets.QMessageBox.warning(
                QtWidgets.QMessageBox(),
                "ID Error",
                "ID가 잘못되었습니다!",
                QtWidgets.QMessageBox.Ok,
            )

    def check_id_valid(self, ID):
        wb = openpyxl.load_workbook(filename="./data/user_profile.xlsx")
        col = wb["user_profile"]["A"][1:]

        for i in range(len(col)):
            if ID == col[i].value:
                wb.close()
                return i + 2
            elif ID < col[i].value:
                wb.close()
                return 0
        wb.close()
        return 0


import resources_rc


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
